### PR TITLE
refactor json-schema code

### PR DESCRIPTION
**Pull request by andersoncardoso**
Solve #13 

This refactors how json-schemas are stored/used, and cut down some code.

For preloading the schemas, from the fixtures, use (the first time only):
```
rake schemas:load
```
This is not necessary, but recommended. If the db entries doesn't exists, they will be lazy-loaded from the fixtures upon request.

### CODE REVIEW

**Comment by leolara** [comment]
@andersoncardoso if prublic/swagger.json is a created resource, shouldn't it be part of the build system? Instead of saved in the repo?

**Comment by andersoncardoso** [comment]
@leolara 
it was there before (since the time we distributed a copy of the swagger-ui, and made the json by hand) , given that it had no practical difference, and changing the c66 build was more trouble, didn't bother to change.

We can change it, though. Does it worth it?

**Comment by leolara** [comment]
@andersoncardoso 

For me swagger is useful for two things:
 + Swagger UI
 + Generating client libraries

If both things work smooth, I guess we should not change a thing

**Comment by leolara** [comment]
@andersoncardoso I like this  PR, it removes a lot of code!! Less is More!!

So, according to me you can merge it

**Comment by leolara** [comment]
@andersoncardoso does this also solve #14 completely or partially?

**Comment by leolara** [comment]
@andersoncardoso is this ready to merge? We can move swagger stuff to another task perhaps?

**Pull request merged**
