### PR TITLE
Helper scripts

### PR DESCRIPTION
**Pull request by coffeejunk**
Add two helper scripts

1. updating the CE/R json schemas
2. publishing a resource envelope

### CODE REVIEW

**Comment by coffeejunk** [comment]
The code isn't exactly pretty (system calls galore) but I'm not trying to win any prizes here.

**Comment by leolara** [comment]
@coffeejunk excellent!

we might change url in the future, like taking out /api/ ; hence I think it is a good idea if the url is in a variable at the top

**Comment by leolara** [comment]
@coffeejunk in update_schema, is there an easy way you can validate the schema before uploading it?

Do it only if it is trivial

**Comment by leolara** [comment]
@coffeejunk please, you put the URL variable in send_resource_envelope also

**Pull request merged**
