### PR TITLE
Update json schemas

### PR DESCRIPTION
**Pull request by coffeejunk**
Updated JSON Schemas for `ce_registry`

### CODE REVIEW

**Comment by leolara** [comment]
@coffeejunk ok to merge. But one question, those files need to be .erb? Is there something dynamic in them?

**Comment by coffeejunk** [comment]
I think we'll wait with the merge until #69 is fixed

**Comment by coffeejunk** [comment]
Regarding your question: there is nothing dynamic going on in these specific schemas, however we have dynamic parts in for example [fixtures/schemas/envelope.json.erb](../blob/b0c1e49f08b6aae825f34b16c72c11457928d5bb/fixtures/schemas/envelope.json.erb) and the current load process requires the files to be named with `.erb` at the end.

**Comment by leolara** [comment]
@coffeejunk once #69 is done, please merge

**Pull request merged**
