### PR TITLE
Default community

### PR DESCRIPTION
**Pull request by coffeejunk**
* The overall default community is (currently) set in the database (see example in [seeds.rb](../blob/ff498c3d0ffb64d633b0bc22e5166c893fa17234/db/seeds.rb#L3)).
* Host specific default communities can be configured in [`config/envelope_communities.json`](../blob/a7e26d4542e0861e1b62fcdcd510819be510e378/config/envelope_communities.json)

Implements #36

### CODE REVIEW

**Comment by coffeejunk** [comment]
Grape parses first the URL parameters, then the request body and fills the `params` variable with the respective values. In case of collision the URL parameter is given precedence.

As a result of this, there are two caveats with the current implementation:

1. If no `envelope_community` is given in the URL and an `envelope_community` is given in the request body, the community from the body will be selected instead of the default community.

1. The behavior where an error is thrown if the `envelope_community` from the URL parameter and the parsed body mismatch is not yet included. A naive implementation would look like this:  
   ```ruby
   def validate_community
     request.body.rewind
     body_community = JSON.parse(request.body.read)['envelope_community']
     unless community == body_community.underscore
       err = ['Missmatching envelope_community']
       json_error! err, nil, :unprocessable_entity
     end
   end
   ```
   
   However it does come at the extra cost of re-parsing the body again. I have to dive deeper into grape's api in order to figure out if there is a way to avoid this. For the time being, if both URL and body parameter are given (and colliding), the URL parameter is given precedence.

**Comment by coffeejunk** [comment]
The API now verifies that the `envelope_community` given in the envelope is the same as either the community defined in the URL (`/{community_name}/resources`) or the default (as defined in `config/envelope_communities.json`). 

I.e. #36 is fully implemented.

**Comment by leolara** [comment]
@coffeejunk please document in markdown the changes to the configuration

**Comment by leolara** [comment]
@coffeejunk ok for me to merge

**Pull request merged**
