### PR TITLE
Support for CER competencies (store and search)

### PR DESCRIPTION
**Pull request by andersoncardoso**
#134 and #135

Add support for publish and search competencies and frameworks

### Samples being used:

check on : 
```
db/seeds/ce_registry/competencies.json
db/seeds/ce_registry/competency_frameworks.json
```

### Schemas: 

```
fixtures/schemas/ce_registry/competency.json
fixtures/schemas/ce_registry/competency_framework.json
````

### Relations 

Currently competency and frameworks are related using the following properties:

- competency
    - `"ceasn:isPartOf": [ "<Framework @id>"]`

- competency_framework
    - `"ceasn:hasChild": [{"@id": "<Competency @id>"}]`
    - `"ceasn:hasTopChild": ["<Competency @id>"]`

### Search fields (json paths):

- competency
    - `$.ceasn:competencyText.en-us`
    - `$.ceasn:description.en-us`
    - `$.ceasn:conceptTerm[0].@id`

- competency_framework
    - `$.ceasn:name.en-us`
    - `$.ceasn:description.en-us`
    - `$.ceasn:publisher[0].ceterms:name`
    - `$.ceasn:localSubject[0].en-us`
     
We also have a "preapared_querie" for searching "competencies inside a given framework". I.e 

`http GET :/ce-registry/competency?framework=<framework-id>`

-----

## Examples: 

- `/ce-registry/competency_framework/search`

s1

-  `/ce-registry/competency_framework/search?fts=<search-term>`

s2
s3

-  `/ce-registry/competency/search`

s4

- `/ce-registry/competency/search?framework=<framework-id>`

s5

- `/ce-registry/competency/search?framework=<framework-id>&fts=<search-term>`

s6

---

OBS: 
To load samples on dev: `rake db:seed:cer_samples`

### CODE REVIEW

**Comment by jbaird123** [comment]
@cwd-mparsons @siuc-nate - Please review @andersoncardoso's comments above and let us know your thoughts.

**Comment by cwd-mparsons** [comment]
@andersoncardoso I had created a separate issue, #156 to  discuss how the ctdlAsn schema would be store, tested, and deployed. We had thought that this schema should be separate from the ctdl schemas. 
See #156 for the questions on organization.

**Comment by siuc-nate** [comment]
http://credreg.net/ctdlasn/schema?profileID=registry

I think I fixed the issues in the first post - let me know.

**Comment by andersoncardoso** [comment]
@siuc-nate tks, I updated the schema, most of the issues are cleared now. 
I'm pasting below the changes I made to fix a few issues, so you can replicate on your side too. 
All these entries are inside `#/definitions/` 
```
"meta:uri": {
    "type": "object",
    "properties": {
        "@id": {
            "$ref": "#/definitions/@id_absolute"
        }
    }
},
"meta:uri_multi": {
    "type": "array",
    "items": {
        "$ref": "#/definitions/meta:uri"
    }
},

"ceterms:name": {
    "$ref": "#/definitions/meta:literal"
},
"ceterms:description": {
    "$ref": "#/definitions/meta:literal"
},
"ceterms:subjectWebpage": {
    "$ref": "#/definitions/meta:uri_multi"
},
"ceterms:socialMedia": {
    "$ref": "#/definitions/meta:uri_multi"
},
```

**Comment by siuc-nate** [comment]
@andersoncardoso I don't think any of those are referenced in the CTDL-ASN validation schema. Those are terms from the CTDL validation schema, though.

**Comment by andersoncardoso** [comment]
@siuc-nate these were referenced on the json-schema. I added these to definitions following the validator err messages. 

s1
s2

**Comment by andersoncardoso** [comment]
@jbaird123 @cwd-mparsons I've updated the PR, this pretty probably closes issues 134 and 135. 

I've made a few assumptions on the data based on the samples I received. I tried to outline them on the PR description. But if later we need to adjust anything, should be easy.

**Pull request merged**
